apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-pvc
  labels:
    app: demo-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
